### ISSUE TITLE
issues about models

### ISSUE THREAD

**Issue by tanyue2019** [prakharguptaz/target-guided-dialogue-coda#2]
Hello, sorry to bother you! Is the generator model you used in "augment_otters_withpaths.py" the "checkpoints_6lendict_wcontains/model.ckpt" provided in the model folder of Google Drive? Why do I get the following error when I load this model?

Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.masked_bias"

**Comment by prakharguptaz** [comment]
For this script specifically, you need to use transformers Version: 2.8.0
There are multiple parts in this codebase and they are sometimes dependent on other existing repos. In those cases the scripts in this repo inherits the dependencies from those repos. Please feel free to create issues for any such dependency or version issue.

**Comment by tanyue2019** [comment]
OK, thanks.！ I also wanted to try version 2.8.0, but it doesn't seem like it can be installed right now. Did you install it using pip?

**Comment by prakharguptaz** [comment]
You might need to downgrade your pytorch version

**Comment by tanyue2019** [comment]
Ok  I will try again. Thanks!

**Comment by tanyue2019** [comment]
Hello , Can I ask what is the content of the folder "/alv2-tcfiltered0.8\u duppathremoved\u len12\u ppl1.3-vorgresp-checkpoint-500"

**Comment by prakharguptaz** [comment]
That is the model pretrained on data augmented using dailydialog. The folder can be found in the google drive.

**Comment by tanyue2019** [comment]
Ok~Thanks!

**Comment by tanyue2019** [comment]
Hi,Sorry to bother you again. Did you use different versions of transformers in different code files？
